=== romankhadka/ThreadStone/v1/result.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BenchmarkResult",
  "type": "object",
  "required": [
    "average",
    "iterations_per_sample",
    "max",
    "min",
    "samples",
    "threads",
    "values",
    "workload"
  ],
  "properties": {
    "average": {
      "type": "number",
      "format": "double"
    },
    "iterations_per_sample": {
      "type": "integer",
      "format": "uint32",
      "minimum": 0.0
    },
    "max": {
      "type": "number",
      "format": "double"
    },
    "min": {
      "type": "number",
      "format": "double"
    },
    "samples": {
      "type": "integer",
      "format": "uint32",
      "minimum": 0.0
    },
    "sig": {
      "type": [
        "string",
        "null"
      ]
    },
    "threads": {
      "type": "integer",
      "format": "uint",
      "minimum": 0.0
    },
    "values": {
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      }
    },
    "workload": {
      "type": "string"
    }
  }
}

=== romankhadka/ThreadStone/examples/results.json
{
  "workload": "Dhrystone",
  "threads": 14,
  "samples": 5,
  "iterations_per_sample": 10000000,
  "values": [
    2305.7371401833225,
    2317.291223161661,
    2275.8786706465726,
    2299.606704851343,
    2292.7691012314663
  ],
  "average": 2298.256568014873,
  "min": 2275.8786706465726,
  "max": 2317.291223161661
}
